# This workflow will build this project

name: Build

on:
  push:
    tags:
      - 'v*.*.*'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: write
  pull-requests: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '20'

    - name: Build
      run: ./build.sh

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.RELEASE_VERSION }}"
        prerelease: false
        title: "Automatic Build"
        files: |
          LICENSE
          README.md
          tapemanager-linux-amd64-${{ env.RELEASE_VERSION }}.tar.gz
